.{
    .bind = .{
        .{
            .address = "127.0.0.1:3000",
            .protocol = .tcp,
            .forward = .{
                .round_robin = .{
                    "127.0.0.1:4000",
                    "127.0.0.1:4001",
                },
            },
        },
        .{
            .address = "127.0.0.1:3001",
            .protocol = .udp,
            .forward = .{
                .weighted_round_robin = .{
                    .{
                        .target = "127.0.0.1:4000",
                        .weight = 2,
                    },
                    .{
                        .target = "127.0.0.1:4001",
                        .weight = 1,
                    }
                },
            },
        },
        .{
            .address = "127.0.0.1:3002",
            .protocol = .tcp,
            .forward = .{
                .ip_hash = .{
                    "127.0.0.1:4000",
                    "127.0.0.1:4001",
                },
            },
        },
        .{
            .address = "127.0.0.1:3003",
            .protocol = .tcp,
            .forward = .{
                .least_connections = .{
                    "127.0.0.1:4000",
                    "127.0.0.1:4001",
                },
            },
        },
        .{
            .address = "127.0.0.1:3004",
            .protocol = .udp,
            .forward = .{
                .weighted_least_connections = .{
                    .{
                        .target = "127.0.0.1:4000",
                        .weight = 2,
                    },
                    .{
                        .target = "127.0.0.1:4001",
                        .weight = 1,
                    }
                },
            },
        },
        .{
            .address = "127.0.0.1:3005",
            .protocol = .tcp,
            .forward = .{
                .least_response_time = .{
                    "127.0.0.1:4000",
                    "127.0.0.1:4001",
                },
            },
        },
        .{
            .address = "127.0.0.1:3006",
            .protocol = .tcp,
            .forward = .{
                .random = .{
                    "127.0.0.1:4000",
                    "127.0.0.1:4001",
                },
            },
        },
    },
}
